spring.application.name=md4_session2_user-service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=1907
spring.jpa.hibernate.ddl-auto=update
